### ISSUE TITLE
Extract core into swift package

### ISSUE THREAD

**Issue by aehlke** [psugihara/FreeChat#29]
The core of rigging up llama2 into a swift environment with pluggable models etc. would be amazing to have as its own SPM package rather than throughout the xcode project.

**Comment by psugihara** [comment]
Most of this is in NPC if you want to take a wack at it. This was my original intention but I think it's actually pretty hairy with the current architecture. The app starts llama.cpp/example/server (lipo'd an x86 and arm64 version as freechat-server) then starts watchdog to kill it when the app exits. I ended up going with the server binary approach so that I can easily get upstream improvements from the llama.cpp gang.

**Comment by aehlke** [comment]
Ah I see, thanks for the context. I'm doing cross-plat mac/iOS so I'll find another way to rig this. Yours works excellently! Haven't found OS work yet that works well like this for Swift.

**Comment by psugihara** [comment]
np, god luck! fwiw this is the best one i found (docs are confusing but llama.cpp is used on that branch) https://github.com/j-f1/LLM-Playground

**Comment by aehlke** [comment]
Thanks. This one is working on iOS and macOS as well https://github.com/guinmoon/LLMFarm
