### ISSUE TITLE
Chat locally with REST API

### ISSUE THREAD

**Issue by greenido** [psugihara/FreeChat#31]
It would be great to be able to chat/query this with REST API so we can bind it into other projects.

**Comment by greenido** [comment]
Ahh... yes please!
Something like the server example would be awesome.

**Comment by psugihara** [comment]
Cool! Also, maybe I misunderstood your original question. Right now you can hit the llama.cpp/examples/server running on localhost:8690 if you're chatting with FreeChat (at some point I want to dynamically bind that port because FreeChat will break if it's taken). The server includes a tiny html front-end as well as a streaming completion API https://github.com/ggerganov/llama.cpp/tree/master/examples/server

**Comment by greenido** [comment]
Sounds good - I'll use this one for now.
Thank you!
